version: '3'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: openmics
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openmics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
