name: All Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    # Set up Docker for testcontainers
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run tests
        working-directory: backend
        run: npm run test
        env:
          NODE_ENV: test
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          RYUK_DISABLED: true
          TESTCONTAINERS_RYUK_DISABLED: true
